#!/usr/bin/env bash
set -euo pipefail

# Writes plan time blocks from today's plan file to a local macOS Calendar
# Reads calendar config and output_dir from config.yaml

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CONFIG="${SCRIPT_DIR}/../config.yaml"

if ! command -v yq &>/dev/null; then
  echo "ERROR: yq not installed"
  exit 1
fi

if [[ ! -f "$CONFIG" ]]; then
  echo "ERROR: config.yaml not found at ${CONFIG}"
  exit 1
fi

if ! SYNC_ENABLED=$(yq '.calendar.sync_enabled // false' "$CONFIG" 2>&1); then
  echo "ERROR: calendar-sync: could not read sync_enabled from config: ${SYNC_ENABLED}" >&2
  exit 1
fi
if [[ "$SYNC_ENABLED" != "true" ]]; then
  echo "Calendar sync disabled in config (calendar.sync_enabled)"
  exit 0
fi

if ! CALENDAR_NAME=$(yq '.calendar.plan_calendar_name // "Daily Plan"' "$CONFIG" 2>&1); then
  echo "ERROR: calendar-sync: could not read plan_calendar_name from config: ${CALENDAR_NAME}" >&2
  exit 1
fi
if ! OUTPUT_DIR=$(yq '.output_dir' "$CONFIG" 2>&1); then
  echo "ERROR: calendar-sync: could not read output_dir from config: ${OUTPUT_DIR}" >&2
  exit 1
fi
if [[ "$OUTPUT_DIR" == "null" || -z "$OUTPUT_DIR" ]]; then
  echo "ERROR: output_dir not set in config.yaml"
  exit 1
fi
OUTPUT_DIR="${OUTPUT_DIR/#\~/$HOME}"

TODAY=$(date +%Y-%m-%d)
TODAY_YEAR=$(date +%Y)
TODAY_MONTH=$(date +%m)
PLAN_FILE="${OUTPUT_DIR}/${TODAY_YEAR}/${TODAY_MONTH}/${TODAY}-plan.md"

echo "=== Calendar Sync ==="

if [[ ! -f "$PLAN_FILE" ]]; then
  echo "ERROR: plan file not found at ${PLAN_FILE}"
  exit 1
fi

# Verify file has YAML frontmatter
first_line=$(head -1 "$PLAN_FILE")
if [[ "$first_line" != "---" ]]; then
  echo "ERROR: no frontmatter in plan file"
  exit 1
fi

# Extract frontmatter between --- delimiters
frontmatter=$(awk '/^---$/{c++;next}c==1' "$PLAN_FILE")

if [[ -z "$frontmatter" ]]; then
  echo "ERROR: empty frontmatter in plan file"
  exit 1
fi

# Escape helper: double quotes -> backslash-escaped for AppleScript strings
esc() { printf '%s' "$1" | tr '\n' ' ' | sed 's/\\/\\\\/g; s/"/\\"/g'; }

cal_escaped=$(esc "$CALENDAR_NAME")

# Ensure calendar exists
if ! osascript -e "tell application \"Calendar\" to if not (exists calendar \"${cal_escaped}\") then make new calendar with properties {name:\"${cal_escaped}\"}" 2>/dev/null; then
  echo "WARNING: Calendar access denied -- grant Terminal/Claude access in System Settings > Privacy > Calendars"
  exit 0
fi

# Delete stale events for today from this calendar
tag="daily-plan:${TODAY}"
if ! osascript <<EOF 2>&1
tell application "Calendar"
  tell calendar "${cal_escaped}"
    set matchingEvents to (every event whose description contains "${tag}")
    if (count of matchingEvents) > 0 then
      repeat with evt in matchingEvents
        delete evt
      end repeat
    end if
  end tell
end tell
EOF
then
  echo "WARNING: failed to delete stale calendar events for ${TODAY} -- duplicates may appear" >&2
fi

# Count plan items with time_block set
if ! item_count=$(echo "$frontmatter" | yq '[.plan_items[] | select(.time_block != null)] | length // 0' 2>&1); then
  echo "WARNING: could not count time-blocked plan items: ${item_count}" >&2
  exit 0
fi
if [[ ! "$item_count" =~ ^[0-9]+$ ]]; then
  echo "WARNING: unexpected item_count value '${item_count}' -- skipping calendar sync" >&2
  exit 0
fi

if [[ "$item_count" -eq 0 ]]; then
  echo "(no time-blocked plan items to sync)"
  exit 0
fi

if ! plan_items_json=$(echo "$frontmatter" | yq -o=json '[.plan_items[] | select(.time_block != null)]' 2>&1); then
  echo "ERROR: could not parse plan_items from frontmatter (yq failed): ${plan_items_json} -- cannot sync calendar" >&2
  exit 1
fi
if ! plan_items_tsv=$(echo "$plan_items_json" | jq -r '.[] | [.text, .time_block, (.app_id // "null")] | @tsv' 2>&1); then
  echo "ERROR: could not parse plan_items from frontmatter (jq failed): ${plan_items_tsv} -- cannot sync calendar" >&2
  exit 1
fi

created=0
while IFS=$'\t' read -r text time_block app_id; do
  [[ -z "$text" ]] && continue

  # Validate time_block format before arithmetic
  if [[ ! "$time_block" =~ ^[0-9]{2}:[0-9]{2}-[0-9]{2}:[0-9]{2}$ ]]; then
    echo "WARNING: skipping malformed time_block '${time_block}' for: ${text}" >&2
    continue
  fi

  # Parse start/end from HH:MM-HH:MM
  start_time="${time_block%-*}"
  end_time="${time_block#*-}"

  # Truncate summary to 80 chars
  summary="${text:0:80}"

  # Build notes field
  notes="${tag}"
  if [[ "$app_id" != "null" && -n "$app_id" ]]; then
    notes=$(printf '%s\n%s' "$notes" "$app_id")
  fi
  notes=$(printf '%s\n%s' "$notes" "Generated by daily-driver")

  # Escape user strings for AppleScript
  summary_escaped=$(esc "$summary")
  notes_escaped=$(esc "$notes")

  # Convert HH:MM to seconds since midnight (locale-independent)
  start_h="${start_time%%:*}"
  start_m="${start_time##*:}"
  start_secs=$(( 10#$start_h * 3600 + 10#$start_m * 60 ))
  end_h="${end_time%%:*}"
  end_m="${end_time##*:}"
  end_secs=$(( 10#$end_h * 3600 + 10#$end_m * 60 ))

  if [[ "$end_secs" -le "$start_secs" ]]; then
    echo "WARNING: calendar-sync: skipping midnight-crossing or zero-duration block '${time_block}'" >&2
    continue
  fi

  # Create event via AppleScript using time-of-day seconds (avoids locale-dependent date coercion)
  if err=$(osascript <<EOF 2>&1
tell application "Calendar"
  tell calendar "${cal_escaped}"
    set startDate to current date
    set time of startDate to ${start_secs}
    set endDate to current date
    set time of endDate to ${end_secs}
    make new event with properties {summary:"${summary_escaped}", start date:startDate, end date:endDate, description:"${notes_escaped}"}
  end tell
end tell
EOF
  ); then
    created=$((created + 1))
  else
    echo "WARNING: failed to create event for '${summary}': ${err}" >&2
  fi
done <<< "$plan_items_tsv"

echo "${created} events synced to '${CALENDAR_NAME}'"
