#!/usr/bin/env bash
set -euo pipefail

# Writes plan time blocks from today's plan file to a local macOS Calendar
# Reads calendar config and output_dir from config.yaml

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CONFIG="${SCRIPT_DIR}/../config.yaml"

if ! command -v yq &>/dev/null; then
  echo "ERROR: yq not installed"
  exit 1
fi

if [[ ! -f "$CONFIG" ]]; then
  echo "ERROR: config.yaml not found at ${CONFIG}"
  exit 1
fi

SYNC_ENABLED=$(yq '.calendar.sync_enabled // false' "$CONFIG")
if [[ "$SYNC_ENABLED" != "true" ]]; then
  echo "Calendar sync disabled in config (calendar.sync_enabled)"
  exit 0
fi

CALENDAR_NAME=$(yq '.calendar.plan_calendar_name // "Daily Plan"' "$CONFIG")
OUTPUT_DIR=$(yq '.output_dir' "$CONFIG")
OUTPUT_DIR="${OUTPUT_DIR/#\~/$HOME}"

TODAY=$(date +%Y-%m-%d)
TODAY_YEAR=$(date +%Y)
TODAY_MONTH=$(date +%m)
PLAN_FILE="${OUTPUT_DIR}/${TODAY_YEAR}/${TODAY_MONTH}/${TODAY}-plan.md"

echo "=== Calendar Sync ==="

if [[ ! -f "$PLAN_FILE" ]]; then
  echo "ERROR: plan file not found at ${PLAN_FILE}"
  exit 1
fi

# Verify file has YAML frontmatter
first_line=$(head -1 "$PLAN_FILE")
if [[ "$first_line" != "---" ]]; then
  echo "ERROR: no frontmatter in plan file"
  exit 1
fi

# Extract frontmatter between --- delimiters
frontmatter=$(awk '/^---$/{c++;next}c==1' "$PLAN_FILE")

if [[ -z "$frontmatter" ]]; then
  echo "ERROR: empty frontmatter in plan file"
  exit 1
fi

# Escape helper: double quotes -> backslash-escaped for AppleScript strings
esc() { printf '%s' "$1" | tr '\n' ' ' | sed 's/\\/\\\\/g; s/"/\\"/g'; }

cal_escaped=$(esc "$CALENDAR_NAME")

# Ensure calendar exists
if ! osascript -e "tell application \"Calendar\" to if not (exists calendar \"${cal_escaped}\") then make new calendar with properties {name:\"${cal_escaped}\"}" 2>/dev/null; then
  echo "WARNING: Calendar access denied -- grant Terminal/Claude access in System Settings > Privacy > Calendars"
  exit 0
fi

# Delete stale events for today from this calendar
tag="daily-plan:${TODAY}"
osascript <<EOF 2>/dev/null || true
tell application "Calendar"
  tell calendar "${cal_escaped}"
    set matchingEvents to (every event whose description contains "${tag}")
    if (count of matchingEvents) > 0 then
      repeat with evt in matchingEvents
        delete evt
      end repeat
    end if
  end tell
end tell
EOF

# Count plan items with time_block set
item_count=$(echo "$frontmatter" | yq '[.plan_items[] | select(.time_block != null)] | length // 0')

if [[ "$item_count" -eq 0 ]]; then
  echo "(no time-blocked plan items to sync)"
  exit 0
fi

created=0
for i in $(seq 0 $((item_count - 1))); do
  # Read from the filtered list of items with time_block
  text=$(echo "$frontmatter" | yq "[.plan_items[] | select(.time_block != null)][$i].text")
  time_block=$(echo "$frontmatter" | yq "[.plan_items[] | select(.time_block != null)][$i].time_block")
  jira=$(echo "$frontmatter" | yq "[.plan_items[] | select(.time_block != null)][$i].jira")

  # Parse start/end from HH:MM-HH:MM
  start_time="${time_block%-*}"
  end_time="${time_block#*-}"

  # Truncate summary to 80 chars
  summary="${text:0:80}"

  # Build notes field
  notes="${tag}"
  if [[ "$jira" != "null" && -n "$jira" ]]; then
    notes=$(printf '%s\n%s' "$notes" "$jira")
  fi
  notes=$(printf '%s\n%s' "$notes" "Generated by daily-driver")

  # Escape user strings for AppleScript
  summary_escaped=$(esc "$summary")
  notes_escaped=$(esc "$notes")

  # Convert HH:MM to seconds since midnight (locale-independent)
  start_h="${start_time%%:*}"
  start_m="${start_time##*:}"
  start_secs=$(( 10#$start_h * 3600 + 10#$start_m * 60 ))
  end_h="${end_time%%:*}"
  end_m="${end_time##*:}"
  end_secs=$(( 10#$end_h * 3600 + 10#$end_m * 60 ))

  # Create event via AppleScript using time-of-day seconds (avoids locale-dependent date coercion)
  if osascript <<EOF 2>/dev/null
tell application "Calendar"
  tell calendar "${cal_escaped}"
    set startDate to current date
    set time of startDate to ${start_secs}
    set endDate to current date
    set time of endDate to ${end_secs}
    make new event with properties {summary:"${summary_escaped}", start date:startDate, end date:endDate, description:"${notes_escaped}"}
  end tell
end tell
EOF
  then
    created=$((created + 1))
  else
    echo "WARNING: failed to create event for: ${summary}"
  fi
done

echo "${created} events synced to '${CALENDAR_NAME}'"
